### ISSUE TITLE
Is there any way to colaborate with you?

### ISSUE THREAD

**Issue by NintendocraftModdingStudios** [Clickism/ClickSigns#2]
Hello,
I discovered your Mod recently and it looks quite nice! I appreciate the design of your signs added by the Mod. But I think, that it would be improving to combine the signs with 3D-Models. I don't know if you know Blockbench but to sum it up : It's a 3D-Model Creator mainly for Minecraft. I have many Ideas to improve your Mod and I am pleased if I could help you because I have already collected some  experience in BB :-)   . Some Ideas would be:
-Adding 3D-Models 
-Self design for the signs
-Other european sign variants *1
-Variable "Autobahn"-Symbols/Numbers *2
* --> Pictures to describe the idea

 *1 https://c8.alamy.com/zoomsde/9/770cf4b018d0404f80dcb6b6e753dd4e/r9x19j.jpg  ;;;;;;; https://cdn.kroati.de/images/uploads/info/anreise/auto/routen/dalmatien/kroatien_anreise-dalmatien-autobahn-slowenien_01_foto-michael-haut.jpg 

*2 https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/A22Swiss.svg/langde-1100px-A22Swiss.svg.png  ;;;;;;;;;;;;;;;;; https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Autoroute_fran%C3%A7aise_36.svg/langde-1100px-Autoroute_fran%C3%A7aise_36.svg.png ;;;;;;;;;;;;; https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Bundesautobahn_5_number.svg/800px-Bundesautobahn_5_number.svg.png 

If you are interested you can text me on GH

**Comment by Clickism** [comment]
Hey, thanks for reaching out. I'm happy to hear you liked the mod. I'm not really planning on adding 3D-Model support since signs themselves 2D, and for the minuscule visual benefit it might bring, it would make the sign creation (and rendering) process/pipeline much more complex. As for your other ideas, you can already achieve them using resourcepack addons to the mod. Feel free to reach me out if you want to collaborate on adding them to the base mod.
